[package]
name = "morse"
version = "0.0.1"
edition = "2024"
authors = ["Dennis Schneck", "dd6ds@eclipso.de"]


[dependencies]
compile-time = "0.2.0"
current_platform = "0.2.0"
fltk = "1.5.9"
gettext-ng = "0.4.1"
once_cell = "1.21.3"
rodio = "0.21.1"
sys-locale = "0.3.2"
