name: Build and Release

on:
  push:
    tags:
      - 'v*'    # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross (for Linux/Windows)
        run: cargo install cross

      - name: Build release binary
        run: |
          if [[ "${{ matrix.target }}" == *linux* || "${{ matrix.target }}" == *windows* ]]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Rename binary
        run: |
          BIN_NAME="my_app"
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            mv target/${{ matrix.target }}/release/${BIN_NAME}.exe ${BIN_NAME}-${{ matrix.target }}.exe
          else
            mv target/${{ matrix.target }}/release/${BIN_NAME} ${BIN_NAME}-${{ matrix.target }}
          fi

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            my_app-${{ matrix.target }}
            my_app-${{ matrix.target }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
