name: Build x86_64-apple-darwin

on:
  push:
    branches:
      - main2
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build for x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: get_version
        run: |
         version=$(grep '^version' Cargo.toml | head -n 1 | sed 's/version = "\(.*\)"/\1/')
         echo "cargo_version=$version" >> $GITHUB_OUTPUT



      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          profile: minimal

      - name: Install Rust target
        run: rustup target add x86_64-apple-darwin

      - name: Build project
        run: cargo build --release --target x86_64-apple-darwin

      - name: Prepare release artifacts
        run: |
          mkdir release
          cp target/x86_64-apple-darwin/release/morse release/morse_apple_x86_64
          cp icon.png release/
          cp *.mo release/
          cd release
          zip -r morse_macos-x86_64-v${{ steps.get_version.outputs.cargo_version }}.zip ./*
          ls -lathr



      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin-binary
          path: target/x86_64-apple-darwin/release/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false


      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/morse_macos-x86_64-v${{ steps.get_version.outputs.cargo_version }}.zip
          asset_name: morse_macos-x86_64-v${{ steps.get_version.outputs.cargo_version }}.zip
          asset_content_type: application/zip

