name: Build x86_64-apple-darwin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build for x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          profile: minimal

      - name: Install Rust target
        run: rustup target add x86_64-apple-darwin

      - name: Build project
        run: cargo build --release --target x86_64-apple-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin-binary
          path: target/x86_64-apple-darwin/release/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

