name: Release Source Code

on:
  push:
    branches: [ "main" ]
    tags:
     - "*.*.*"
  pull_request:
    branches: [ "main" ]
    tags:
     - "*.*.*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip source code
        run: |
        TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
          zip -r source-code.zip . -x "*.git*"   # Exclude git files

      - name: Create GitHub Release and Upload Source ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: source-code.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
